### ISSUE TITLE
PSI-Name Preferred and Interim

### ISSUE THREAD

**Issue by trishorts** [topdownproteomics/proteoform-nomenclature-standard#15]
from jscottrell:  Section 3 Rule 5: (Also Section 5) The Unimod 'PSI-MS Name' is the preferred name. The 'Interim name' should only be used when the PSI-MS Name is empty.

**Comment by stefanks** [comment]
From http://www.unimod.org/fields.html

- PSI-MS Name: The standard short name for a modification, agreed by members of the protein modification workgroup of the Proteomics Standards Initiative. This field is display only, and may sometimes be copied from the interim name suggested by the record curator. Must be unique within the database.
- Interim Name: Descriptive, one word name, suitable for use in software applications. If you adhere the Naming guidelines, it is possible that the Interim Name will be adopted as the "official" PSI-MS Name.

I would be ok with this, except this may complicate the rules a bit, since the interim name is always there, and the PSI-MS name is not. 

Any thoughts?

**Comment by acesnik** [comment]
We decided to use the unimod interim name, published [here](https://pubs.acs.org/doi/10.1021/acs.jproteome.7b00851).
