### ISSUE TITLE
info key: do not allow square brackets

### ISSUE THREAD

**Issue by sgibb** [topdownproteomics/proteoform-nomenclature-standard#20]
Currently the standard for the info key doesn't allow pipe characters:

> Descriptors may not contain the pipe character.

I would suggest to forbid square brackets as well, e.g.

> Descriptors may not contain the pipe character nor square brackets.

Otherwise parsing the tags would be more difficult. An alternative would be to surround the info description by quotation marks, e.g. `SEQ[info: "Some comment about this amino acid[X]"]UENCE`

**Comment by stefanks** [comment]
It's an unnecessary restriction, since parsing could be done by requiring the first bracket to be closed, and, necessarily the inner brackets would have to be closed as well. We need to allow those, because Unimod has cases with brackets.

The only corner-case is a weird description where a ] character occurs without a preceding [ , but this seems to be improbable enough not to merit a separate rule.

What does everyone think?

**Comment by hollenstein** [comment]
You could allow square brackets only if they occur as a pair in the proper order "[" "]". Although this is a corner-case it would break any parser that relies on a proper hierarchy of opening and closing square brackets.

**Comment by stefanks** [comment]
Yes, I believe this is reasonable

**Comment by sgibb** [comment]
Ok, I am happy with this solution. You could close this issue if you like.
